<?
return [
    'viewPath' => 'application.views.mail',
    'layoutPath' => 'application.views.layouts',
    'baseDirPath' => 'webroot.images.mail',
    'savePath' => 'webroot.assets.mail',
    'testMode' => false,
    'layout' => 'mail',
    'CharSet' => 'UTF-8',
    'AltBody' => EO::t('YiiMailer','You need an HTML capable viewer to read this message.'),
    'language' => [
		'authenticate'         => EO::t('YiiMailer','SMTP Error: Could not authenticate.'),
		'connect_host'         => EO::t('YiiMailer','SMTP Error: Could not connect to SMTP host.'),
		'data_not_accepted'    => EO::t('YiiMailer','SMTP Error: Data not accepted.'),
		'empty_message'        => EO::t('YiiMailer','Message body empty'),
		'encoding'             => EO::t('YiiMailer','Unknown encoding: '),
		'execute'              => EO::t('YiiMailer','Could not execute: '),
		'file_access'          => EO::t('YiiMailer','Could not access file: '),
		'file_open'            => EO::t('YiiMailer','File Error: Could not open file: '),
		'from_failed'          => EO::t('YiiMailer','The following From address failed: '),
		'instantiate'          => EO::t('YiiMailer','Could not instantiate mail function.'),
		'invalid_address'      => EO::t('YiiMailer','Invalid address'),
		'mailer_not_supported' => EO::t('YiiMailer',' mailer is not supported.'),
		'provide_address'      => EO::t('YiiMailer','You must provide at least one recipient email address.'),
		'recipients_failed'    => EO::t('YiiMailer','SMTP Error: The following recipients failed: '),
		'signing'              => EO::t('YiiMailer','Signing Error: '),
		'smtp_connect_failed'  => EO::t('YiiMailer','SMTP Connect() failed.'),
		'smtp_error'           => EO::t('YiiMailer','SMTP server error: '),
		'variable_set'         => EO::t('YiiMailer','Cannot set or reset variable: ')
	],
];